site_name: PT-Ranking
nav:
    - Home: index.md
    - How-to-Start:
      - how_to_start/Get_Started.md
      - how_to_start/Configuration.md
      - how_to_start/Develop_A_New_Model.md
    - Data: data/data.md
    - Metric: metric/metric.md
    - LTR_Adhoc:
      - ltr_adhoc/about.md
      - ltr_adhoc/Lambda_Framework.md
    - LTR_Diversification:
        - ltr_diversification/about.md
        - ltr_diversification/Direct_Metric_Optimization.md
    - LTR_Adversarial:
      - ltr_adversarial/about.md
      - ltr_adversarial/IRGAN.md
    - LTR_GBM:
      - ltr_gbm/about.md
      - ltr_gbm/LambdaMART.md

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - attr_list
repo_name: 'PT-Ranking'
repo_url: 'https://github.com/wildltr/ptranking/'
